name: todos_api
description: The interface and models for an API providing access to todos.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  meta: ^1.3.0
  uuid: ^3.0.4

dev_dependencies:
  build_runner: ^2.0.0
